module.exports = {
  "Cesar Leiva": [
    "Adam Hinckley",
    "Brandon Vilaychith",
    "Corey Gumbs",
    "Gabriel Smaniego",
    "Jordan Stoddard",
    "Nolan Allen",
    "Scott Bren",
    "Troy Amlee"
  ],
  "Jeffrey Kang": [
    "Adam McKenney",
    "Brian Garcia-Felix",
    "Daniel Ferrer",
    "Gannon LeBlanc",
    "Justin Lowry",
    "McKay Bonham",
    "Oguz Akkas",
    "Ryan Boris",
    "Sean Flannigan",
    "Wanda Evans"
  ],
  "Joe Stanfield": [
    "Andre Myrick",
    "Brian Gregorius",
    "David Soto",
    "Hargobind Atwal",
    "Kat Johnson-Fries",
    "Melinda Yeager",
    "Oleksandr Stasyvev",
    "Ryan Clausen",
    "Sean Won",
    "Wesley McCrary"
  ],
  "Kam Bowman": [
    "Angelo Deleon",
    "Brian Williams",
    "Drew Johnson",
    "Hunter Smith",
    "Katherine Fitzpatrick",
    "Melissa McDonald",
    "Orlando Castillo",
    "Ryan Walker",
    "Shawn Antonucci",
    "Yanrong Xu"
  ],
  "Kevin Brack": [
    "Ayinde Williams",
    "Carlo Clamucha",
    "Edd Burke",
    "Ian Cameron",
    "Katy Hollobaugh",
    "Michael Checo",
    "Pedro Montesinos",
    "Sabrina Gear",
    "Yusuf Nafey"
  ],
  "Luis Martinez": [
    "Barbara Hunter",
    "Carlos Cruz",
    "Edward Jeong",
    "Jacob Brennan",
    "Kyran McCann",
    "Mikaela Currier",
    "Peter Pham",
    "Samuel Ko",
    "Steve Alverson",
    "Zachary Arney",
  ],
  "Margo Nikolaisen": [
    "Blake Koennecker",
    "Carlos Lantigua",
    "Edwin Torres",
    "Jake Thomas",
    "Lajawanti Dhake",
    "Muhammad Malik",
    "Phil Hart",
    "Samuel Machat",
    "Steven O'Neill"
  ],
  "Sumayyah Asgar": [
    "Brad Mortensen",
    "Chad Jemmett",
    "Elvis Ibarra",
    "Jasmine Galang",
    "Lee Len Formento",
    "Mustafa Inaya",
    "Quan Nguyen",
    "Samuel Partner",
    "Steven Smodish",
  ],
  "Tai Le": [
    "Brandon Grych",
    "Chance Embrey-Farquhar",
    "Erica Thacker",
    "Joe Bugajski",
    "Liv Johnson",
    "Nick Kruger",
    "Rahul Desai",
    "Sarah Tennis",
    "Thomas Utsey"
  ],
  "William DiFulvio": [
    "Brandon Strellis",
    "Conner Hoessly",
    "Christopher Cedeno",
    "Frank Benevento",
    "John Graniero",
    "Lola Heffernan",
    "Riley Brown",
    "Savannah Greuel",
    "Toua Xiong"
  ]
}
